# Generated by Django 2.1 on 2018-08-16 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capitulo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitulo',
            name='nombre',
            field=models.CharField(default=None, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='capitulo',
            name='norma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='norma.Norma'),
        ),
    ]
