# Generated by Django 2.1 on 2018-08-18 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capitulo', '0002_auto_20180816_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitulo',
            name='ponderacion',
            field=models.IntegerField(null=True),
        ),
    ]
