# Generated by Django 2.1 on 2018-08-18 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capitulo', '0003_capitulo_ponderacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('nivel', models.IntegerField()),
                ('capitulo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='capitulo.Capitulo')),
            ],
        ),
        migrations.CreateModel(
            name='TipoPregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'capitulo_tipo_pregunta',
            },
        ),
        migrations.AddField(
            model_name='pregunta',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capitulo.TipoPregunta'),
        ),
    ]
