# Generated by Django 2.1 on 2018-08-18 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capitulo', '0005_auto_20180818_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='ponderacion',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='sugerencia',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
