# Generated by Django 2.1 on 2018-08-21 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capitulo', '0007_auto_20180818_1813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipopregunta',
            old_name='descripcion',
            new_name='tipo',
        ),
        migrations.RemoveField(
            model_name='tipopregunta',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='tipopregunta',
            name='fecha_edicion',
        ),
        migrations.AddField(
            model_name='tipopregunta',
            name='esp',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
