import { StyleSheet, Dimensions } from 'react-native'
import {
  blanco,
  blancoTotal,
  darkGrey,
  midGrey,
  acento,
  primario,
  bodyGrey,
  bodyFontSize,
  fontSizeLarger,
  fontSizeLarge,
  fontSizeMedium,
  fontSizeSmall,
  fontSizeSmaller,
  fontSizeTiny,
  conFontSize,
  gridHeight,
  fontWeightBold,
  fontWeightLight,
  globalPaddingTiny,
  globalPaddingSmall,
  globalPadding,
  globalPaddingMedium,
  globalPaddingLarge,
  globalPaddingLarger,
  globalPaddingJumbo,
} from './vars'

const CardStyles = {
  CardContainer: {
    width: '44%',
    height: 172,
    marginVertical: 10,
    marginHorizontal: 10,
    borderRadius: 24,
    backgroundColor: acento,
    padding: globalPaddingMedium,
    shadowOffset: {
      width: 0,
      height: 5,
    },
    shadowRadius: 10,
    shadowColor: acento,
    shadowOpacity: 0.4,
  },
  CardContainerFullWidth: {
    width: '94%',
    height: 172,
    marginVertical: 10,
    marginHorizontal: 10,
    borderRadius: 24,
    backgroundColor: acento,
    padding: globalPaddingMedium,
    shadowOffset: {
      width: 0,
      height: 5,
    },
    shadowRadius: 10,
    shadowColor: acento,
    shadowOpacity: 0.4,
  },
  CapitulosCard: {
    width: '94%',
    height: 172,
    marginVertical: 10,
    marginHorizontal: 10,
    borderRadius: 24,
    backgroundColor: primario,
    padding: globalPaddingMedium,
    shadowOffset: {
      width: 0,
      height: 5,
    },
    shadowRadius: 10,
    shadowColor: acento,
    shadowOpacity: 0.4,
  },
  PreguntasCard: {
    width: '94%',
    height: 64,
    marginVertical: 10,
    marginHorizontal: 10,
    borderRadius: 32,
    backgroundColor: blancoTotal,
    paddingVertical: globalPaddingSmall,
    paddingHorizontal: globalPaddingMedium, 
    shadowOffset: {
      width: 0,
      height: 5,
    },
    shadowRadius: 10,
    shadowColor: acento,
    shadowOpacity: 0.1,
    alignContent: 'flex-start',
    justifyContent: 'center',
  },
  CardTitle: {
    color: blanco,
    fontSize: fontSizeSmall,
    fontWeight: '800',
  },
  CardTitleDark: {
    color: darkGrey,
    fontSize: fontSizeMedium,
    fontWeight: '800',
  },
  PreguntasTitle: {
    color: darkGrey,
    fontSize: fontSizeSmall,
    fontWeight: '800',
  },
}
function createStyles(overrides = {}) {
  return StyleSheet.create({ ...CardStyles, ...overrides })
}
export default {
  createStyles,
}
