# Generated by Django 2.1 on 2018-08-23 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_analista'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='persona',
            name='telefonos',
            field=models.ManyToManyField(blank=True, to='user.Telefono'),
        ),
    ]
