# Generated by Django 2.1 on 2018-08-24 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('norma', '0002_norma_ponderada'),
        ('user', '0004_auto_20180823_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='analista',
            name='normas',
            field=models.ManyToManyField(blank=True, to='norma.Norma'),
        ),
    ]
