# Generated by Django 2.1 on 2018-09-01 04:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0007_analista_profesional'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='usuarios',
            field=models.ManyToManyField(blank=True, related_name='usuarios', to=settings.AUTH_USER_MODEL),
        ),
    ]
