# Generated by Django 2.1 on 2018-08-31 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0006_auto_20180829_0145'),
        ('norma', '0002_norma_ponderada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Licencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analistas', models.IntegerField()),
                ('profesionales', models.IntegerField()),
                ('duracion', models.IntegerField()),
                ('fecha_vencimiento', models.DateField()),
            ],
            options={
                'db_table': 'licencia',
            },
        ),
        migrations.CreateModel(
            name='LicenciaCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Cliente')),
                ('licencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licencia.Licencia')),
                ('norma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='norma.Norma')),
            ],
            options={
                'db_table': 'licencia_cliente',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('analistas', models.IntegerField()),
                ('profesionales_min', models.IntegerField()),
                ('profesionales_max', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='licenciacliente',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licencia.Plan'),
        ),
    ]
